name: Lint, Test and Build
on: [push, workflow_dispatch]
jobs:
    lint_test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install node js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependices
              run: |
                    npm ci
                    echo "Test NPM Lint"
                    npm run lint
    testing:
        needs: lint_test
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install node js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: |
                    npm ci
                    echo "Testing Test"
                    npm run test
    test_building:
        needs: [lint_test, testing]
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install Node js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: |
                    npm ci
                    echo "Testing Build"
                    npm run build
                    echo "Building"